"""empty message

Revision ID: 1507699d186a
Revises: ce209e6e732d
Create Date: 2018-04-09 11:21:27.264440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1507699d186a'
down_revision = 'ce209e6e732d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_content_key', 'comment', type_='unique')
    op.drop_constraint('comment_email_key', 'comment', type_='unique')
    op.drop_constraint('comment_post_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_fkey', 'comment', 'post', ['post'], ['id'])
    op.create_unique_constraint('comment_email_key', 'comment', ['email'])
    op.create_unique_constraint('comment_content_key', 'comment', ['content'])
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
