"""empty message

Revision ID: 59dd15c27d67
Revises: a667a914f350
Create Date: 2018-04-09 09:59:58.932980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59dd15c27d67'
down_revision = 'a667a914f350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('post', 'update_time')
    op.drop_column('post', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
