"""empty message

Revision ID: a13a18c05cfc
Revises: 4dc0fb87df7a
Create Date: 2018-04-10 18:34:29.403688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13a18c05cfc'
down_revision = '4dc0fb87df7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('status', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'status')
    # ### end Alembic commands ###
