"""empty message

Revision ID: d5d52a25bf96
Revises: a13a18c05cfc
Create Date: 2018-04-11 10:47:01.042955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d52a25bf96'
down_revision = 'a13a18c05cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'view_count')
    # ### end Alembic commands ###
